name: Build Executable

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger this workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile main.py
          # If you have a spec file:
          # pyinstaller my_script.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Tic-Tac-Toe
          path: dist/Tic-Tac-Toe  # Adjust this according to your output folder
